### ISSUE TITLE
"audit.json" file created when using vscode+tabbyml

### ISSUE THREAD

**Issue by CleyFaye** [TabbyML/tabby#2237] opened 2024-05-24 13:31 UTC
**Describe the bug**
When launching VSCode with the TabbyML extension active, a file named "audit.json" is created in the root of each projects.

I'm not sure exactly what triggers this behavior.

**Information about your version**
The VSCode extension is version 1.6.2.
I do not have access to the tabby server right now; I'll update this later. However, as this happens client-side (on a different machine) I am not sure it is relevant. Still, it should be 0.11.1 on windows with cuda122 from memory.

**Information about your GPU**
The server is running on windows with an RTX 3080Ti (12GB VRAM). I doubt I can run "nvidia-smi" there.

**Additional context**
The content of the file:

```json{
    "keepSettings": {
        "type": 1,
        "amount": 30
    },
    "auditFilename": "audit.json",
    "hashType": "md5",
    "extension": ".log",
    "files": [
        {
            "date": 1716556954963,
            "name": "/home/cleyfaye/.tabby-client/agent/logs/20240524.0.log",
            "hash": "951e003596f4088c6c5706627bde8eda"
        }
    ]
}
```

(the path is not really sensitive data so I left it as-is).

It is very possible that I missed a setting, but I didn't see anything relevant on the web interface or in the doc.

**Comment by wsxiaoys** [comment] 2024-05-24 16:22
seems to be related to Winston integration @icycodes

**Comment by Zhincore** [comment] 2024-05-25 13:21
Happens to me too

**Comment by icycodes** [comment] 2024-05-28 03:37
This bug has been confirmed. It may occur if the user enabled the filesystem log by setting the log level to a non-default value in `~/.tabby-client/agent/config.toml`.

**Comment by icycodes** [comment] 2024-05-28 06:56
This issue should be resolved in the latest update of the Tabby VSCode extension version 1.6.3. 
Please consider updating the extension and testing it out. Feel free to reopen if you encounter any further issues.

**Closed by icycodes** 2024-05-28 06:56 UTC
Labels: bug

**Comment by Kamilcuk** [comment] 2024-06-14 17:21
This also happens when using tabby-agent with nvim-lspconfig as described in https://github.com/neovim/nvim-lspconfig/blob/37f362ef42d1a604d332e8d3d7d47593852b4313/doc/server_configurations.md?plain=1#L11483 . What should I do to disable creation of audit.json?

**Comment by Kamilcuk** [comment] 2024-06-27 13:13
Great! Thank you!

czw., 27 cze 2024 o 13:39 Zhiming Ma ***@***.***> napisał(a):
