### ISSUE TITLE
Intel Arc / XPU support

### ISSUE THREAD

**Issue by itlackey** [TabbyML/tabby#631] opened 2023-10-25 02:12 UTC
I would be great to be able to run Tabby locally on my Intel Arc GPU. 

**Additional context**

This is currently possible in tools like llama.cpp by compiling with OpenCL support. I have no idea how that would (or could) translate to Rust.

---
Please reply with a 👍 if you want this feature.

**Comment by itlackey** [comment] 2023-10-26 14:29
If I am understanding this code correctly (crates/llama-cpp-bindings/build.rs), I believe we just need a switch for OpenCL to enable Intel GPU support. 

If OpenCL is selected, then add the build args as described in this section of the llama.cpp docs:
https://github.com/ggerganov/llama.cpp#clblast

**Comment by wsxiaoys** [comment] 2023-10-26 18:06
Hi @itlackey, unfortunately, I don't have an Intel Arc card to try out. If anyone has a card and is interested in giving it a try, please feel free to do so! Happy to help if any problems arise.

**Comment by itlackey** [comment] 2023-10-26 18:28
I have a card but no Rust experience and basic understanding of the underlying C++ libraries. I could try adjusting the code but I'm not entirely sure of what the entire list of changes would be. Do you know if there would need additonal changes beyond altering the build args in build.rs?

**Comment by wsxiaoys** [comment] 2023-10-26 18:42
I think the first step would be following the instructions here: https://github.com/TabbyML/tabby#-contributing to make it build in your local dev environment. Then you could tune the building flags in llama-cpp-bindings’s build.rs a bit to make it compiles with opencl support.

**Comment by itlackey** [comment] 2023-10-26 18:44
Sounds reasonable, I will give it a try as soon as I get a chance.

**Comment by cromefire** [comment] 2023-11-25 18:11
Trying to get this working (more specifically Intel iGPU support and also ROCm support) and but after compiling it I just get a "501 Error: Not Implemented" (in Docker). No errors during build though. Any idea what went wrong?

**Comment by cromefire** [comment] 2023-11-25 20:34
Put it all in a pull request here: #895

**Comment by itlackey** [comment] 2023-11-25 20:48
Nice work!! I put this on the back burner due to not being able to get decent performance using OpenCL with llama.cpp but it looks like you found a better approach. Thanks for pushing this forward!

**Comment by cromefire** [comment] 2023-11-25 21:27
Well I still have to get it work, right now every sort of configuration for tabby just returns HTTP 501

**Comment by itlackey** [comment] 2023-11-25 21:52
Does llama.cpp work in the gpu with these compiler options? If not, get llama.cpp working as expected and then port that to the Tabby build settings. Skimming through the changes to Tabby, it seems like you're in the right track.

**Comment by hungle-i3** [comment] 2024-02-08 05:19
Hello everyone, I am working on supporting intel CPU Arch by integrating intel openapi platform to tabby. Just wanted to know whether there is any update on this. I love to contribute to this for getting  it  done. Thanks.

**Comment by cromefire** [comment] 2024-02-08 08:20
Upstream (llama.cpp) has to support it. As soon as it has that I have stuff already prepared. Alternatively if it'll be integrated faster Vulkan compute can also be used, but the same deal, it has to be merged first.

Haven't followed those PRs though, so if one of them has merged, tell me and I'll get it done. As soon as Tabby's fork of llama.cpp has been updated of course.

**Comment by itlackey** [comment] 2024-02-08 08:20
I have not spent time on it in a while. I did see SYCL is now supported in llama.cpp and works well on Intel.

**Comment by wsxiaoys** [comment] 2024-02-08 08:24
It's updated in recent release (0.8): https://github.com/TabbyML/llama.cpp

**Comment by hungle-i3** [comment] 2024-02-17 12:32
Hi @wsxiaoys, llama.cpp fork binding  with the tabby releases (0.8/0.9) hasn't updated to the  SYCL support.
At the moment, for intel architecture, I  am planning to support  2 following features as recommendation from llama.cpp https://github.com/ggerganov/llama.cpp/blob/master/README-sycl.md

- onemkl: For intel CPU https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl.html#gs.4lpxoo.
- onesycl: Backend for intel GPU: Waiting  for llama.cpp fork to be upgraded. 

Is it good to go?

**Comment by cromefire** [comment] 2024-02-17 12:35
> onemkl: For intel CPU https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl.html#gs.4lpxoo.

Not sure whether that's even worth it as I think the default CPU stuff already uses AVX and so on I think.

**Comment by hungle-i3** [comment] 2024-02-17 13:09
@cromefire , will enable Intel BLAS (Intel10_64lp) at onemkl feature as Intel guideline https://www.intel.com/content/www/us/en/content-details/791610/optimizing-and-running-llama2-on-intel-cpu.html

**Comment by cromefire** [comment] 2024-02-17 13:12
> @cromefire , will enable Intel BLAS (Intel10_64lp) at onemkl feature as Intel guideline https://www.intel.com/content/www/us/en/content-details/791610/optimizing-and-running-llama2-on-intel-cpu.html

Would definitely still suggest to try it first if it even helps with anything and if it does maybe check for regression, because otherwise it might be easier to just use it by default rather than adding it as a "backend". 2 CPU backbends would kinda be confusing...

**Comment by hungle-i3** [comment] 2024-02-17 16:03
Thanks @cromefire for your suggestion.
Pull request at  https://github.com/TabbyML/tabby/pull/1474

**Comment by wsxiaoys** [comment] 2024-04-21 05:34
Closing as vulkan support is preferred for such use cases.

**Closed by wsxiaoys** 2024-04-21 05:34 UTC
Labels: enhancement
