### ISSUE TITLE
Codellama 7B OOM on A30

### ISSUE THREAD

**Issue by mydipan396** [TabbyML/tabby#541] opened 2023-10-12 12:52 UTC
When installing Codellama 7b on a device with 24GB of VRAM like the A30, it may exceed the available VRAM capacity and result in an error. In such cases, you can try using CTranslate2 without utilizing the ggml model.

Error Info:
2023-10-12 20:37:08 2023-10-12T12:37:08.293510Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:183: Listening at 0.0.0.0:8080
2023-10-12 20:39:00 terminate called after throwing an instance of 'std::runtime_error'
2023-10-12 20:39:00   what():  CUDA failed with error out of memory

**Comment by wsxiaoys** [comment] 2023-10-12 15:56
Hi, could you share the docker command?

**Comment by mydipan396** [comment] 2023-10-13 01:48
> Hi, could you share the command starting tabby?

**Comment by mydipan396** [comment] 2023-10-13 01:49
To install and run Codellama directly using Docker, you can add the --model TabbyML/CodeLlama-7B flag.

docker run -it \
  --gpus all -p 8080:8080 -v $HOME/.tabby:/data \
  tabbyml/tabby \
  serve --model TabbyML/CodeLlama-7B --device cuda

**Comment by mydipan396** [comment] 2023-10-13 01:52
> Hi, could you share the command starting tabby?

To install and run Codellama directly using Docker, add the --model TabbyML/CodeLlama-7B flag.

docker run -it
--gpus all -p 8080:8080 -v $HOME/.tabby:/data
tabbyml/tabby
serve --model TabbyML/CodeLlama-7B --device cuda

**Comment by wsxiaoys** [comment] 2023-10-13 06:17
On a GPU with a capability of >= 8.0 (which A30 has), the inference engine will attempt to load the model in int8 mode. For CodeLlama-7B, it roughly requires around 8GB of VRAM.

Could you please confirm if you have sufficient VRAM to run such a model? Additionally, could you share the output of `nvidia-smi` before and after running the above Docker command?

**Comment by JohanVer** [comment] 2023-10-18 07:43
I experience the same problem on a L40 GPU.  It happens with Llama but also with Mistral.
I noticed that after startup the GPU Mem is at the expected <8GB, however with every tabby completion request the memory grows. It feels that there is a memory leak somewhere.
When I downgrade to V0.2.0 I do not notice the problem.

**Comment by wsxiaoys** [comment] 2023-10-18 09:30
@JohanVer, have you tried version v0.2.2? Does it also exhibit the issue you described?

There are a few significant changes between v0.2.0 and v0.2.2 that might affect VRAM usage, so I’d like to confirm

**Comment by mydipan396** [comment] 2023-10-18 11:50
When deploying the Codellama 7B model on a Windows system, there seems to be a continuous increase in VRAM usage during inference. However, when deploying on a Linux system, the VRAM usage remains stable. On the other hand, When calling the Llamacode 7B model on Linux, there is a significant increase in CPU usage. However, when using the Starcoder model, the CPU usage remains stable.

**Comment by wsxiaoys** [comment] 2023-10-18 16:18
Hello @mydipan396, could you please test the CodeLlama 7B model on Linux with versions 0.2.0 and 0.2.2 to determine if the out-of-memory (OOM) issue still persists? This is in reference to the comments provided by @JohanVer earlier.

**Comment by mydipan396** [comment] 2023-10-19 02:58
Re-testing, it is indeed a version issue, independent of the operating system. There are problems when installing version 0.2.2, but updating to the latest version, 0.3.0, resolves the problem.

**Comment by wsxiaoys** [comment] 2023-10-19 04:51
To confirm, does the "OOM" problem on CodeLLama-7B disappear after upgrading to v0.3.0? Is that correct?

**Comment by JohanVer** [comment] 2023-10-19 06:53
Hi @wsxiaoys ,
I gave all versions a try now using a L40 GPU. 
Every version higher than 0.2.0 (0.2.1, 0.2.2 and also 0.3.0)  leads to growing memory consumption (higher with every completion prompt).
It seems that the version 0.3.0 lets the memory grow slower in the beginning but eventually the problem remains.

**Comment by wsxiaoys** [comment] 2023-10-19 07:06
Hello, @JohanVer. Thank you for conducting these experiments. I do have a potential culprint commit between versions 0.2.0 and 0.2.1, which may potentially increase GPU RAM usage when setting a higher parallelism for GPU replicas (https://github.com/TabbyML/tabby/commit/b3b498624cabeaee61c47b6fdfdf82ec3ddf3be1).

As a temporary solution, please continue using v0.2.0 for your setup. I will investigate the issue further and provide an update once it's resolved.

**Comment by JohanVer** [comment] 2023-10-19 07:15
Thanks @wsxiaoys  for the investigating the problem and for the awesome project :) 
Let me know if I can help with testing.

**Comment by wsxiaoys** [comment] 2023-10-19 07:30
Here is the Docker image [0.3.0-rc.1](https://hub.docker.com/layers/tabbyml/tabby/0.3.1-rc.0/images/sha256-bb60ea62981fdc107a3c8832707958c73ea5fbfa7070c6440c73ea097dde257c?context=explore). Please give it a try and see if the issue is resolved!

**Comment by wsxiaoys** [comment] 2023-10-20 03:22
Hi @mydipan396 @ClarkWain could you also test with [0.3.0-rc.1](https://hub.docker.com/layers/tabbyml/tabby/0.3.1-rc.0/images/sha256-bb60ea62981fdc107a3c8832707958c73ea5fbfa7070c6440c73ea097dde257c?context=explore) to see if it fixed the issue for you?

**Comment by ClarkWain** [comment] 2023-10-21 08:58
> Hi @mydipan396 @ClarkWain could you also test with [0.3.1-rc.0](https://hub.docker.com/layers/tabbyml/tabby/0.3.1-rc.0/images/sha256-bb60ea62981fdc107a3c8832707958c73ea5fbfa7070c6440c73ea097dde257c?context=explore) to see if it fixed the issue for you?

I have tried it, the memory usage of CodaLlama7B is within the range of 7GB~8GB, and there is no OOM anymore. Thanks

**Comment by wsxiaoys** [comment] 2023-10-21 19:34
Released in v0.3.1 https://github.com/TabbyML/tabby/releases/tag/v0.3.1

**Closed by wsxiaoys** 2023-10-21 19:34 UTC
Labels: enhancement
