### ISSUE TITLE
Panic when indexing a repository from config

### ISSUE THREAD

**Issue by sinnerJoe** [TabbyML/tabby#1697] opened 2024-03-19 14:29 UTC
**Describe the bug**
I added the repo of my company's project to `~/.tabby/config.toml`, then I ran `tabby scheduler --now`.

I got a panic.
```
Building dataset...
100%|████████████████████████████████████████| 17776/17776 [02:47<00:00, 105.88it/s]Indexing repositories...
 50%|████████████████████▍                   |  8974/17776 [00:01<00:01, 5268.63it/s]thread 'main' panicked at crates/tabby-scheduler/src/index.rs:86:14:
Range is known valid
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: tabby_scheduler::index::index_repositories
   4: tabby_scheduler::job_index
   5: tabby::main::{{closure}}
   6: tokio::runtime::park::CachedParkThread::block_on
   7: tabby::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Information about your version**
tabby 0.9.0

**Information about your GPU**
Apple M2 Max

**Additional context**
I installed tabby using `brew`.
I tried to run the command both when the server is turned on and off.

**Comment by wsxiaoys** [comment] 2024-03-19 23:58
cc @boxbeam

**Comment by boxbeam** [comment] 2024-03-20 23:32
@sinnerJoe Thanks for reporting this! I've made a PR to improve this error message so we can get more information about the issue. You can either wait for this PR to be merged, or clone the repository and checkout the branch `tag-range-error` locally. A nightly build will also be released soon which includes this patch.

If you want to build locally, you can follow this guide after checking out the branch `tag-range-error`: https://github.com/TabbyML/tabby/blob/main/CONTRIBUTING.md

Once you have it running from a local build, please reproduce the error, and it should now display which file it originates from and the range that it was trying to read from. Please share the contents of that file and the error message with us, and we should be able to determine the cause.

**Comment by sinnerJoe** [comment] 2024-03-22 22:24
Hey @boxbeam ,
I ran the scheduler again with the nightly changes. 
Here is the output
```
100%|████████████████████████████████████████| 17910/17910 [03:20<00:00, 89.38it/s]Indexing repositories...
 51%|████████████████████▌                   |  9108/17910 [00:30<00:29, 296.15it/s]thread 'main' panicked at crates/tabby-scheduler/src/index.rs:79:28:
Failed to read content '18446744073709551615..18446744073709551615' from 'app/models/concerns/with_actor.rb'
stack backtrace:
   0:        0x1076d246c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc44f794219052ac6
   1:        0x107702f44 - core::fmt::write::h3be8b1c9593e07b4
   2:        0x1076eaad8 - std::io::Write::write_fmt::h95a1e6c5537a96b5
   3:        0x1076d22c4 - std::sys_common::backtrace::print::h7b809dd1f18ea674
   4:        0x1076ec9b0 - std::panicking::default_hook::{{closure}}::he339b0dd23f9052e
   5:        0x1076ec730 - std::panicking::default_hook::he9ee42fa25c512f5
   6:        0x1076ecdd4 - std::panicking::rust_panic_with_hook::hd4ada112570991e5
   7:        0x1076d2a50 - std::panicking::begin_panic_handler::{{closure}}::h3f2b6a80c2b7e617
   8:        0x1076d26a0 - std::sys_common::backtrace::__rust_end_short_backtrace::hc0b94e2951df3fae
   9:        0x1076ecb64 - _rust_begin_unwind
  10:        0x107922344 - core::panicking::panic_fmt::h0ed3af01737be6a9
  11:        0x104b0e524 - tabby_scheduler::index::read_range_or_panic::{{closure}}::h49a3cdf91bbb4916
                               at /Users/synch/Projects/tabby/crates/tabby-scheduler/src/index.rs:79:28
  12:        0x104aa16f0 - core::option::Option<T>::unwrap_or_else::h2a73bd9d0fd24787
                               at /private/tmp/rust-20240215-5649-scngkd/rustc-1.76.0-src/library/core/src/option.rs:976:21
  13:        0x104aa040c - tabby_scheduler::index::read_range_or_panic::h96943a16cd3243ee
                               at /Users/synch/Projects/tabby/crates/tabby-scheduler/src/index.rs:77:5
  14:        0x104b0e62c - tabby_scheduler::index::from_source_file::{{closure}}::h20ba0c08da588c37
                               at /Users/synch/Projects/tabby/crates/tabby-scheduler/src/index.rs:86:20
  15:        0x104b0e418 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h8cc4892cbe8e0f16
                               at /private/tmp/rust-20240215-5649-scngkd/rustc-1.76.0-src/library/core/src/ops/function.rs:294:13
  16:        0x104aa3a54 - core::iter::traits::iterator::Iterator::find_map::check::{{closure}}::h0dba2185549da053
                               at /private/tmp/rust-20240215-5649-scngkd/rustc-1.76.0-src/library/core/src/iter/traits/iterator.rs:2958:32
  17:        0x104a9ba6c - core::iter::traits::iterator::Iterator::try_fold::hea928347c746b517
                               at /private/tmp/rust-20240215-5649-scngkd/rustc-1.76.0-src/library/core/src/iter/traits/iterator.rs:2462:21
  18:        0x104a9b8f0 - core::iter::traits::iterator::Iterator::find_map::hb6b202309205bb64
                               at /private/tmp/rust-20240215-5649-scngkd/rustc-1.76.0-src/library/core/src/iter/traits/iterator.rs:2964:9
  19:        0x104ac7258 - <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next::h7d481faffd61b5b2
                               at /private/tmp/rust-20240215-5649-scngkd/rustc-1.76.0-src/library/core/src/iter/adapters/filter_map.rs:63:9
  20:        0x104a9fe04 - tabby_scheduler::index::index_repositories::h3831c1a751a57280
                               at /Users/synch/Projects/tabby/crates/tabby-scheduler/src/index.rs:48:20
  21:        0x104ab6304 - tabby_scheduler::job_index::h539cf7d9af0f325f
                               at /Users/synch/Projects/tabby/crates/tabby-scheduler/src/lib.rs:62:15
  22:        0x1044bc424 - tabby_scheduler::scheduler::{{closure}}::h5c50f3d114f02ed0
                               at /Users/synch/Projects/tabby/crates/tabby-scheduler/src/lib.rs:19:9
  23:        0x10473fce0 - tabby::main::{{closure}}::hebbb0581bcde6435
                               at /Users/synch/Projects/tabby/crates/tabby/src/main.rs:165:18
  24:        0x104651224 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::hefd6030d773ea36c
                               at /Users/synch/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.0/src/runtime/park.rs:282:63
  25:        0x10465107c - tokio::runtime::coop::with_budget::he823f78d1f8a7a86
                               at /Users/synch/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.0/src/runtime/coop.rs:107:5
  26:        0x10465107c - tokio::runtime::coop::budget::h536d68efb3970dc5
                               at /Users/synch/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.0/src/runtime/coop.rs:73:5
  27:        0x10465107c - tokio::runtime::park::CachedParkThread::block_on::hd6ee5bd584afd597
                               at /Users/synch/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.0/src/runtime/park.rs:282:31
  28:        0x1045eadb0 - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::h11b773875305ef5c
                               at /Users/synch/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.0/src/runtime/context/blocking.rs:66:9
  29:        0x10456dea0 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::h6d791d1b4f83d729
                               at /Users/synch/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  30:        0x104550c80 - tokio::runtime::context::runtime::enter_runtime::h7eef42cb0e4ec6f0
                               at /Users/synch/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.0/src/runtime/context/runtime.rs:65:16
  31:        0x10456de44 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h21bb7b0846855dd1
                               at /Users/synch/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  32:        0x1048227b8 - tokio::runtime::runtime::Runtime::block_on::heab1a384205ce2bb
                               at /Users/synch/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.0/src/runtime/runtime.rs:350:45
  33:        0x104a42bbc - tabby::main::h608b54641abf8abc
                               at /Users/synch/Projects/tabby/crates/tabby/src/main.rs:142:5
  34:        0x10476eb48 - core::ops::function::FnOnce::call_once::h9391ba9d6ab2bb42
                               at /private/tmp/rust-20240215-5649-scngkd/rustc-1.76.0-src/library/core/src/ops/function.rs:250:5
  35:        0x104736ed0 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha717af1cd728df6f
                               at /private/tmp/rust-20240215-5649-scngkd/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:155:18
  36:        0x1048ea4bc - std::rt::lang_start::{{closure}}::h9bc23c84a28b7e4f
                               at /private/tmp/rust-20240215-5649-scngkd/rustc-1.76.0-src/library/std/src/rt.rs:166:18
  37:        0x1076eca50 - std::panicking::try::h3128bce4d588bc41
  38:        0x1076d4654 - std::rt::lang_start_internal::h57a49fa80dd8b904
  39:        0x1048ea488 - std::rt::lang_start::h9dbc879776692b61
                               at /private/tmp/rust-20240215-5649-scngkd/rustc-1.76.0-src/library/std/src/rt.rs:165:17
  40:        0x104a42c58 - _main
```

These are the contents of the file it fails on(thankfully it isn't a file with business logic 😆 ):
```ruby
# frozen_string_literal: true

module Events
  module WithActor
    extend ActiveSupport::Concern

    def actor
      case data.actor.type
      when "Actor::System" then ::Actor.system
      when "Actor::Scheduler" then ::Actor.scheduler
      when "Actor::UnknownUser" then ::Actor.unknown_user
      else
        User.find_by(strong_id: data.actor.strong_id) || ::Actor.unknown_user
      end
    end
  end
end

```

**Comment by boxbeam** [comment] 2024-03-25 16:56
This looks like a case of overflow... The file is nowhere near 18446744073709551615 bytes long, and 18446744073709551616 (2^64, max unsigned long) is only 1 greater. I poked around in our code and we never seem to be subtracting from this field, so it suggests that this is a tree-sitter bug (maybe specifically tree-sitter Ruby?). I'd recommend [opening a bug with them](https://github.com/tree-sitter/tree-sitter-ruby).

**Closed** 2024-03-26 21:40 UTC
Labels: bug-unconfirmed
