### ISSUE TITLE
Idea extension wanted

### ISSUE THREAD

**Issue by lvdahsuai** [TabbyML/tabby#311] opened 2023-07-25 02:19 UTC
**Please describe the feature you want**
Idea extension wanted

**Additional context**

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment] 2023-07-25 02:21
@icycodes is actively working on this and it’s expected to have preview version in coming days, stay tuned :)

Closing as duplicate of #76

**Closed by wsxiaoys** 2023-07-25 02:21 UTC
Labels: enhancement
