### ISSUE TITLE
Tabby plugin for JetBrains IDE is always under initialization.

### ISSUE THREAD

**Issue by danny-su** [TabbyML/tabby#2650] opened 2024-07-15 13:23 UTC
**Describe the bug**
JetBrains IDE plugin version: 1.6.2
<img width="371" alt="image" src="https://github.com/user-attachments/assets/1b366687-6e00-4bae-8efd-977141938b1a">

**Information about your version**
tabby 0.13.1

**Information about your GPU**
MPS

**Comment by icycodes** [comment] 2024-07-16 01:57
Hi, @danny-su. 

I'm working on identifying the cause of this issue. Could you please provide more information?

1. Could you help check if Tabby has logged any errors? You can find the logs by navigating to `Help -> Show Log in Files` and filtering them by `com.tabbyml.intellijtabby`. Here's a link to more detailed instructions: [troubleshooting documentation](https://tabby.tabbyml.com/docs/extensions/troubleshooting/#intellij-platform-ides).

2. Also, have you tried opening an empty directory or project to see if the issue persists there as well?

**Comment by danny-su** [comment] 2024-07-16 07:11
@icycodes 
```
java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.vfs.VirtualFile.getUrl()" because the return value of "com.intellij.openapi.editor.Editor.getVirtualFile()" is null
	at com.tabbyml.intellijtabby.lsp.TextDocumentSync$Companion.buildDidOpenTextDocumentParams(TextDocumentSync.kt:54)
	at com.tabbyml.intellijtabby.lsp.TextDocumentSync.initSync(TextDocumentSync.kt:25)
	at com.tabbyml.intellijtabby.lsp.TextDocumentSync.startSync(TextDocumentSync.kt:18)
	at com.tabbyml.intellijtabby.lsp.LanguageClient.processInitializeResult(LanguageClient.kt:81)
	at com.tabbyml.intellijtabby.lsp.ConnectionService.initialize(ConnectionService.kt:85)
	at com.tabbyml.intellijtabby.lsp.ConnectionService.access$initialize(ConnectionService.kt:30)
	at com.tabbyml.intellijtabby.lsp.ConnectionService$initialize$1.invokeSuspend(ConnectionService.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by ioniks** [comment] 2024-07-16 07:39
I have the same issue with the same message. On windows 11 / PhpStorm

**Comment by icycodes** [comment] 2024-07-16 08:36
I just uploaded version 1.6.3 to fix this issue.  
Since it may take up to 2 days for it to be approved by JetBrains, please consider reverting to an older version or building it manually (on the main or release-intellij-1.6 branch) before it becomes available on the marketplace.

**Comment by ioniks** [comment] 2024-07-16 09:02
@icycodes Test with the zip you have sended to me on slack.

The bug is fixed on this new version 👍

**Closed** 2024-08-02 13:00 UTC
Labels: bug
