### ISSUE TITLE
idea plugin cannot initialize tabby

### ISSUE THREAD

**Issue by newyorkthink** [TabbyML/tabby#521] opened 2023-10-08 12:46 UTC
![image](https://github.com/TabbyML/tabby/assets/87791643/d8ee583d-0a80-4d45-811a-f040297a3e7f)

i am install node ,but it show cannot initial

**Comment by newyorkthink** [comment] 2023-10-08 12:57
![image](https://github.com/TabbyML/tabby/assets/87791643/1cd6b995-ec8a-4a13-af71-c95a3fe0adc2)

**Comment by icycodes** [comment] 2023-10-09 04:51
Hi, @newyorkthink 

The Tabby IntelliJ Plugin currently only searches the `PATH` environment variable for the Node binary. It does not check the settings of the Node.js plugin.

It seems that you are using fnm as your Node version manager. Tools like nvm and fnm require you to execute a command whenever you open a new bash terminal to update the PATH environment variable. Typically, this command is added to your `~/.bashrc` file. However, IntelliJ IDEs do not execute this command when they start. You can try moving this command to your `~/.profile` file, which runs when you log in to Linux.

To check the value of the PATH environment variable that the Tabby plugin gets, you can open "Help" -> "Open Log In Editor" and search for com.tabbyml.intellijtabby in the logs.

We are planning to add a setting that allows users to specify the path of the Node binary in next release.

**Comment by newyorkthink** [comment] 2023-10-09 05:55
> Hi, @newyorkthink
> 
> The Tabby IntelliJ Plugin currently only searches the `PATH` environment variable for the Node binary. It does not check the settings of the Node.js plugin.
> 
> It seems that you are using fnm as your Node version manager. Tools like nvm and fnm require you to execute a command whenever you open a new bash terminal to update the `PATH` environment variable. Typically, this command is added to your `~/.bashrc` file. However, IntelliJ IDEs do not execute this command when they start. You can try moving this command to your `~/.profile` file, which runs when you log in to Linux.
> 
> To check the value of the `PATH` environment variable that the Tabby plugin gets, you can open `Help` -> `Open Log In Editor` and search for `com.tabbyml.intellijtabby` in the logs.
> 
> We are planning to add a setting that allows users to specify the path of the Node binary in next release.

![image](https://github.com/TabbyML/tabby/assets/87791643/8b95cc01-5714-46e8-9db2-3c35fa7fb1e7)

i add path in .profile, but it not work again.

and this is not find , 'Open Log In Editor' in 2023.2.2 not its 
To check the value of the PATH environment variable that the Tabby plugin gets, you can open Help -> Open Log In Editor and search for com.tabbyml.intellijtabby in the logs.

**Comment by icycodes** [comment] 2023-10-09 06:44
You can try `Help -> Show Log in Files` instead, or search for some actions about `Log`, or locate the log file according to [this document](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs), and open the log file in your text editor.

Some screenshots for reference:  
( IntelliJ IDEA 2023.2.2 (Community Edition) Build #IC-232.9921.47 )
![Screenshot from 2023-10-09 14-25-10](https://github.com/TabbyML/tabby/assets/13573879/7339dc4a-a2f7-40a6-9ce6-20cd86837085)
![Screenshot from 2023-10-09 14-27-08](https://github.com/TabbyML/tabby/assets/13573879/2fe7a36f-c9c7-43b2-9aec-2db722443469)

---


And note that you should log out and log in Linux again after updating `~/.profile` file.

**Comment by newyorkthink** [comment] 2023-10-09 06:52
> You can try `Help -> Show Log in Files` instead, or search for some actions about `Log`, or locate the log file according to [this document](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs), and open the log file in your text editor.
> 
> Some screenshots for reference: ( IntelliJ IDEA 2023.2.2 (Community Edition) Build #IC-232.9921.47 ) ![Screenshot from 2023-10-09 14-25-10](https://user-images.githubusercontent.com/13573879/273511950-7339dc4a-a2f7-40a6-9ce6-20cd86837085.png) ![Screenshot from 2023-10-09 14-27-08](https://user-images.githubusercontent.com/13573879/273511974-2fe7a36f-c9c7-43b2-9aec-2db722443469.png)
> 
> And note that you should log out and log in Linux again after updating `~/.profile` file.

in the idea ultra, i not find `Show Log in Files`

https://github.com/TabbyML/tabby/assets/87791643/33b5b1a1-6504-4e74-b8ce-1b24c1d15107

**Comment by newyorkthink** [comment] 2023-10-09 07:33
> `Show Log in File Manager` is what you are looking for, `File Manager / Files / Finder` may vary based on your OS.

is open this
![image](https://github.com/TabbyML/tabby/assets/87791643/d73d08b1-7b8f-434a-a291-4a45e87bafde)

**Comment by leamsigc** [comment] 2023-10-09 09:38
Solution for me was to create a  link
 - `PATH` Variable for node is not set 
```
ln -s "$(which node)" /usr/local/bin/node
```

**Comment by newyorkthink** [comment] 2023-10-09 10:30
> Solution for me was to create a link
> 
> * `PATH` Variable for node is not set
> 
> ```
> ln -s "$(which node)" /usr/local/bin/node
> ```

it cannot fix, when i whick node, the folder is change
![image](https://github.com/TabbyML/tabby/assets/87791643/9871896d-f723-44ff-b1a1-3ea1fb655929)
2401_1696846997483 the number folder it will change, so, when i restart os , the link ,is invaild
![image](https://github.com/TabbyML/tabby/assets/87791643/039f21c9-b0a3-424c-a71f-e5f257df824c)

**Comment by leamsigc** [comment] 2023-10-09 11:59
It seems that the problem is fnm it self then, can you use nvm ? I use nvm and for me this work `sudo ln -s "$(which node)" /usr/local/bin/node
`

**Comment by newyorkthink** [comment] 2023-10-09 12:07
> It seems that the problem is fnm it self then, can you use nvm ? I use nvm and for me this work `sudo ln -s "$(which node)" /usr/local/bin/node `

Maybe wait tabby new version to fixed

**Comment by wsxiaoys** [comment] 2023-10-15 05:25
Fixed in 0.6.0

**Closed by wsxiaoys** 2023-10-15 05:25 UTC
Labels: bug
