### ISSUE TITLE
Can't test/build Tabby on openSUSE Tumbleweed, OpenSSL version error

### ISSUE THREAD

**Issue by RiQuY** [TabbyML/tabby#1774] opened 2024-04-06 11:08 UTC
**Describe the bug**

I tried setting up the git repo to build it myself to be able to use Tabby with "--feature vulkan" because I couldn't find in the docs a container that supports Vulkan, but I receive and error about the OpenSSL version while executing the tests.

```
This crate is only compatible with OpenSSL (version 1.0.1 through 1.1.1, or 3), or LibreSSL 2.5
  through 3.8.1, but a different version of OpenSSL was found. The build is now aborting
  due to this version mismatch.
```

`RUST_BACKTRACE=full cargo test -- --skip golden` full output:
https://gist.github.com/RiQuY/94e1202d6079d7de71a5300e973f5b28

**Information about your version**

The version of Tabby is the last commit available on main https://github.com/TabbyML/tabby/commit/3a7009d968b17287dbd47ae0b749e04cd386dc74

openssl version
OpenSSL 3.1.4 24 Oct 2023 (Library: OpenSSL 3.1.4 24 Oct 2023)

**Steps to reproduce**

1.  Use OpenSUSE Tumbleweed
2.  Clone the repo and `cd` to the tabby folder: `git clone --recurse-submodules https://github.com/TabbyML/tabby`
3. Install the requirements mentioned in https://github.com/TabbyML/tabby/blob/main/CONTRIBUTING.md#local-setup (protobuf-devel)
4. Run `cargo test -- --skip golden`
5. Tests fail/interrupt.

**Information about your GPU/System**

```
System:
  Host: localhost.localdomain Kernel: 6.8.2-1-default arch: x86_64 bits: 64
    compiler: gcc v: 13.2.1
  Desktop: KDE Plasma v: 6.0.3 tk: Qt v: N/A wm: kwin_wayland dm: 1: GDM
    2: SDDM note: stopped Distro: openSUSE Tumbleweed 20240403
CPU:
  Info: 8-core model: AMD Ryzen 7 1700X bits: 64 type: MT MCP arch: Zen rev: 1
    cache: L1: 768 KiB L2: 4 MiB L3: 16 MiB
  Speed (MHz): avg: 3088 high: 3410 min/max: 2200/3400 boost: enabled cores:
    1: 3219 2: 3273 3: 3199 4: 2911 5: 2995 6: 2797 7: 3410 8: 2794 9: 2875
    10: 3180 11: 3074 12: 2982 13: 2967 14: 3094 15: 3252 16: 3400
    bogomips: 108629
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: Blackmagic Design Intensity Pro 4K driver: N/A pcie:
    speed: 2.5 GT/s lanes: 4 bus-ID: 04:00.0 chip-ID: bdbd:a139
  Device-2: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
    vendor: XFX Pine driver: amdgpu v: kernel arch: RDNA-1 pcie: speed: 16 GT/s
    lanes: 16 ports: active: DP-1,HDMI-A-1 empty: DP-2,DP-3 bus-ID: 0a:00.0
    chip-ID: 1002:731f
  Device-3: Logitech StreamCam
    driver: hid-generic,snd-usb-audio,usbhid,uvcvideo type: USB rev: 3.2
    speed: 5 Gb/s lanes: 1 bus-ID: 6-4.2:4 chip-ID: 046d:0893
  Display: wayland server: X.org v: 1.21.1.11 with: Xwayland v: 23.2.4
    compositor: kwin_wayland driver: X: loaded: modesetting unloaded: fbdev,vesa
    dri: radeonsi gpu: amdgpu display-ID: 0
  Monitor-1: DP-1 model: LG (GoldStar) 27GL850 res: 2560x1440 dpi: 109
    diag: 685mm (27")
  Monitor-2: HDMI-A-1 model: Acer G237HL res: 1920x1080 dpi: 96
    diag: 584mm (23")
  API: EGL v: 1.5 platforms: device: 0 drv: radeonsi device: 1 drv: swrast
    surfaceless: drv: radeonsi wayland: drv: radeonsi x11: drv: radeonsi
    inactive: gbm
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.3 glx-v: 1.4
    direct-render: yes renderer: AMD Radeon RX 5700 XT (radeonsi navi10 LLVM
    18.1.2 DRM 3.57 6.8.2-1-default) device-ID: 1002:731f display-ID: :1.0
  API: Vulkan v: 1.3.280 surfaces: xcb,xlib,wayland device: 0
    type: discrete-gpu driver: N/A device-ID: 1002:731f
```

**Additional context**
I think this problem originates because my distro is a rolling release and Tabby requires an outdated OpenSSL package.

Removing the **Cargo.lock** file on the root folder of the project and running `RUST_BACKTRACE=full cargo test -- --skip golden` again made the SSL error go away but then the tests stopped again because of the following error:

```
❯ RUST_BACKTRACE=full cargo test -- --skip golden
   Compiling hyper-tls v0.5.0
   Compiling hyper-rustls v0.24.2
   Compiling zstd-safe v6.0.6
error[E0432]: unresolved import `zstd_sys::ZSTD_cParameter::ZSTD_c_experimentalParam6`
   --> /home/ricardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zstd-safe-6.0.6/src/lib.rs:609:13
    |
609 |             ZSTD_c_experimentalParam6 as ZSTD_c_targetCBlockSize,
    |             -------------------------^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |             |
    |             no `ZSTD_c_experimentalParam6` in `ZSTD_cParameter`
    |             help: a similar name exists in the module: `ZSTD_c_experimentalParam1`

   Compiling cxx v1.0.120
   Compiling stacker v0.1.15
For more information about this error, try `rustc --explain E0432`.
   Compiling pest_derive v2.7.9
error: could not compile `zstd-safe` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

Related issue: https://github.com/gyscos/zstd-rs/issues/268

The `zstd-safe` compilation error originates from the **tantivy** dependency which needs a new version to be released, a workaround for this is locking the current **tantivy** version to a specific commit in the Cargo.toml file or waiting for a new release. https://github.com/quickwit-oss/tantivy/issues/2339#issuecomment-2039414309

```
# tantivy = { version = "0.21.0" }
tantivy = { git = "https://github.com/quickwit-oss/tantivy/", rev = "4e79e11007b6c9fc3d3965beefe33e1ffcf641d3" }
```

PD: Still not working after doing the workaround, I receive the following compilation errors on the tests:
```
warning: llama-cpp-bindings@0.10.0-dev.0: Compiler version doesn't include clang or GCC: "c++" "--version"
error[E0038]: the trait `Document` cannot be made into an object
   --> crates/tabby/src/services/code.rs:131:20
    |
131 | fn get_field(doc: &Document, field: Field) -> String {
    |                    ^^^^^^^^ `Document` cannot be made into an object
    |
note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>
   --> /home/ricardo/.cargo/git/checkouts/tantivy-f70b7ea03dadae9a/4e79e11/src/schema/document/mod.rs:180:10
    |
180 |     type Value<'a>: Value<'a> + Clone
    |          ^^^^^ the trait cannot be made into an object because it contains the generic associated type `Value`
    = help: the following types implement the trait, consider defining an enum where each variant holds one of these types, implementing `Document` for this new enum and using it instead:
              std::collections::BTreeMap<tantivy::schema::Field, tantivy::schema::OwnedValue>
              std::collections::HashMap<tantivy::schema::Field, tantivy::schema::OwnedValue>
              tantivy::TantivyDocument
```
Full output: https://gist.github.com/RiQuY/3740a894fbdc8f6da6e93d6e50cb4f77

**Comment by RiQuY** [comment] 2024-04-06 12:09
Removing the Cargo.lock file on the root folder of the project and running `RUST_BACKTRACE=full cargo test -- --skip golden` again made the SSL error go away but then the tests stopped again because of the following error:

```
❯ RUST_BACKTRACE=full cargo test -- --skip golden
   Compiling hyper-tls v0.5.0
   Compiling hyper-rustls v0.24.2
   Compiling zstd-safe v6.0.6
   Compiling axum v0.6.20
   Compiling libsqlite3-sys v0.27.0
   Compiling graphql-parser v0.3.0
   Compiling prost v0.11.9
   Compiling psm v0.1.21
   Compiling portable-atomic v1.6.0
   Compiling num-integer v0.1.46
   Compiling termcolor v1.4.1
   Compiling number_prefix v0.4.0
   Compiling cxxbridge-flags v1.0.120
   Compiling sql_query_builder v2.1.0
   Compiling semver v1.0.22
   Compiling hash-ids v0.2.1
error[E0432]: unresolved import `zstd_sys::ZSTD_cParameter::ZSTD_c_experimentalParam6`
   --> /home/ricardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zstd-safe-6.0.6/src/lib.rs:609:13
    |
609 |             ZSTD_c_experimentalParam6 as ZSTD_c_targetCBlockSize,
    |             -------------------------^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |             |
    |             no `ZSTD_c_experimentalParam6` in `ZSTD_cParameter`
    |             help: a similar name exists in the module: `ZSTD_c_experimentalParam1`

   Compiling cxx v1.0.120
   Compiling stacker v0.1.15
For more information about this error, try `rustc --explain E0432`.
   Compiling pest_derive v2.7.9
error: could not compile `zstd-safe` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by wsxiaoys** [comment] 2024-04-06 16:42
Could you try building with `static-ssl` feature turned-on? e.g `cargo build —features static-ssl`

**Comment by RiQuY** [comment] 2024-04-06 17:12
> Could you try building with `static-ssl` feature turned-on? e.g `cargo build --features static-ssl`

Should I do that using the code of the main branch or the code with the workaround applied?

**Comment by wsxiaoys** [comment] 2024-04-06 17:38
it’s an existing feature (and being used in manylinux2014 build). You can run it from main branch directly.

**Comment by wsxiaoys** [comment] 2024-04-06 17:39
it’s an existing feature (and being used in manylinux2014 build). You can run it from main branch directly.

**Comment by wsxiaoys** [comment] 2024-04-06 17:40
it’s an existing feature (and being used in manylinux2014 build). You can run it from main branch directly.

**Comment by wsxiaoys** [comment] 2024-04-06 17:40
it’s an existing feature (and being used in manylinux2014 build). You can run it from main branch directly.

**Comment by RiQuY** [comment] 2024-04-06 17:58
> it’s an existing feature (and being used in manylinux2014 build). You can run it from main branch directly.

I tried with the manylinux2014 binary provided in the project releases passing --feature vulkan but that binary only supports --feature cpu flag.

As you suggested, executing the following commands without running the tests, the program manages build and run without errors:
```
git clone --recurse-submodules https://github.com/TabbyML/tabby
cd tabby
cargo build --features static-ssl
cargo run --features static-ssl --features vulkan serve --model TabbyML/StarCoder-3B --chat-model TabbyML/WizardCoder-3B --device vulkan --webserver
```

Output:
```
warning: function `make_pagination_query` is never used
  --> ee/tabby-db/src/lib.rs:85:4
   |
85 | fn make_pagination_query(
   |    ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `tabby-db` (lib) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.38s
     Running `target/debug/tabby serve --model TabbyML/StarCoder-3B --chat-model TabbyML/WizardCoder-3B --device vulkan --webserver`
2024-04-06T17:46:22.110030Z  INFO tabby::serve: crates/tabby/src/serve.rs:123: Starting server, this might take a few minutes...
2024-04-06T17:46:22.119794Z  INFO tabby::services::code: crates/tabby/src/services/code.rs:53: Index is ready, enabling server...    
ggml_vulkan: Found 1 Vulkan devices:
Vulkan0: AMD Radeon RX 5700 XT (RADV NAVI10) | uma: 0 | fp16: 1 | warp size: 64
ggml_gallocr_reserve_n: reallocating Vulkan0 buffer from size 0.00 MiB to 195.00 MiB
ggml_gallocr_reserve_n: reallocating Vulkan_Host buffer from size 0.00 MiB to 11.00 MiB
ggml_gallocr_reserve_n: reallocating Vulkan0 buffer from size 0.00 MiB to 195.00 MiB
ggml_gallocr_reserve_n: reallocating Vulkan_Host buffer from size 0.00 MiB to 11.00 MiB
2024-04-06T17:46:32.301730Z  INFO tabby::routes: crates/tabby/src/routes/mod.rs:35: Listening at 0.0.0.0:8080

  JWT secret is not set

  Tabby server will generate a one-time (non-persisted) JWT secret for the current process.
  Please set the TABBY_WEBSERVER_JWT_TOKEN_SECRET environment variable for production usage.


2024-04-06T17:51:00.219661Z  INFO tabby_webserver::cron::scheduler: ee/tabby-webserver/src/cron/scheduler.rs:52: Running scheduler job...
Syncing 0 repositories...
Building dataset...
Indexing repositories...
2024-04-06T17:51:00.329048Z  INFO tabby_webserver::cron::scheduler: ee/tabby-webserver/src/cron/scheduler.rs:36: Next time for scheduler job is 2024-04-06T20:01:00+02:00

```

I think this works as a solution, sorry about the confusion, I didn't know about the --features static-ssl flag and ended up going through a rabbit hole of dependency errors thinking that they were related to the issue.

Can you add to the docs that to be able to run Tabby in openSUSE you need to install `protobuf-devel` dependency, use `cargo build --features static-ssl` and skips the tests? Thanks.

**Comment by RiQuY** [comment] 2024-04-06 18:24
I'm not sure why but the --feature static-ssl only works when running `cargo run` on the main branch, I tried using 0.9.1 but I tabby crashes with this error:
https://gist.github.com/RiQuY/df42b395eb9fe29ba13c94006377d6eb

I'm fine running main branch if it works but I wanted to let you know anyway,

**Comment by wsxiaoys** [comment] 2024-04-06 18:43
Thanks for reporting - i think the major reason is vulkan support (w/testing) is added after 0.9 release. it shall be included as part of 0.10, though.

**Comment by RiQuY** [comment] 2024-04-06 18:45
> Thanks for reporting - i think the major reason is vulkan support (w/testing) is added after 0.9 release. it shall be included as part of 0.10, though.

Vulkan supports makes Tabby usable in my system, with cpu is too slow. Thank you for the help, you can close the issue if you consider it solved.

**Comment by wsxiaoys** [comment] 2024-04-07 04:58
I think the remaining issue is that the manylinux2014 binary for Vulkan should work. I'm adding @boxbeam to take a look.

**Comment by boxbeam** [comment] 2024-04-16 17:11
Unable to reproduce vulkan only working on CPU, so I will close this issue since it seems everything is resolved

**Closed by boxbeam** 2024-04-16 17:11 UTC
Labels: bug-unconfirmed
